syntax = "proto3";

option csharp_namespace = "ProductService.Protos";

service GrpcProducts
{
    rpc CreateProductModel(CreateProductModelRequest) returns (CreateProductModelResponse);                     //DONE
    rpc CreateProduct(CreateProductRequest) returns (StatusResponse);                                           //DONE

    rpc GetProductsByIds(GetProductsByIdsRequest) returns (GetProductsByIdsResponse);                           //DONE
    rpc GetAllProductsByOwnerId(GetAllProductsByOwnerIdRequest) returns (GetAllProductsByOwnerIdResponse);      //DONE
    
    rpc ReassignProductWithCard(ReassignProductWithCardRequest) returns (StatusResponse);
    rpc UpdateProductById(UpdateProductRequest) returns (StatusResponse);
    
    rpc ArchiveProduct() returns ();
    rpc UnarchiveProduct() returns ();
    
    rpc DeleteProductsByIds(DeleteProductsRequest) returns (StatusResponse);
    rpc DeleteImagesFromProduct(DeleteImagesFromProductRequest) returns (StatusResponse);
    
    
    rpc GetCards() returns();
    rpc GetCardsRaw() returns();
}

message ProductGrpc
{
    string productId = 1;   
    string ownerId = 2;
    string parentCardId = 3;
    ProductType type = 4;
    string name = 5;
    string description = 6;    
    int32 price = 7;
    int32 stockQuantity = 8;
    string createdAt = 9;
    string updatedAt = 10;
    repeated string imageURLs = 11;
    repeated ProductAttributeGrpc attributes = 12;
    bool canBeOrdered = 13;
    bool isArchived = 14;
}

enum ProductType{
    UNKNOWN_TYPE = 0;
    LIQUID = 1;
    VAPE = 2;
}

enum AttributeKey{  
    UNKNOWN_KEY = 0;
    BRAND = 1;
    VOLUME = 2;
}

message ProductAttributeGrpc
{ 
    AttributeKey key = 1; 
    string value = 2;
}

message StatusResponse
{
    bool status = 1;
    string reason = 2;
}

message CreateProductModelRequest
{    
    string ownerId = 1;
}

message CreateProductModelResponse
{    
    StatusResponse status = 1;
    string productId = 2;
}

message CreateProductRequest
{    
    string productId = 1;   
    ProductType type = 2;
    string name = 3;
    string description = 4;    
    int32 price = 5;
    int32 stockQuantity = 6;
    repeated ProductAttributeGrpc attributes = 7;
}

message GetProductsByIdsRequest
{
	repeated string productsIds = 1;
}

message GetProductsByIdsResponse
{
	StatusResponse status = 1;
	repeated ProductGrpc products = 2;
}

message GetAllProductsByOwnerIdRequest
{
    string ownerId = 1;
}

message GetAllProductsByOwnerIdResponse
{  
    StatusResponse status = 1;
    repeated ProductGrpc products = 2;
}

message ReassignProductWithCardRequest{
    string productId = 1;
    string cardId = 2;
}










message DeleteProductsRequest
{
    repeated string productsIds = 1;
}

message UpdateProductRequest
{
    string productId = 1;   
    ProductType type = 2;
    string name = 3;
    string description = 4;    
    int32 price = 5;
    int32 stockQuantity = 6;
    repeated ProductAttributeGrpc attributes = 7;
}

message DeleteImagesFromProductRequest
{
    string productId = 1;
    repeated string imageURLs = 2;
}