syntax = "proto3";

option csharp_namespace = "ProductService.Protos";

service GrpcProducts
{
    rpc CreateProduct(CreateProductRequest) returns (StatusResponse);
    rpc GetProductsByIds(GetProductsByIdsRequest) returns (GetProductsByIdsResponse);
    rpc GetAllProductsByOwnerId(GetAllProductsByOwnerIdRequest) returns (GetAllProductsByOwnerIdResponse);
    rpc GetProductById(GetProductRequest) returns (GetProductResponse);
    rpc UpdateProductById(UpdateProductRequest) returns (StatusResponse);
    rpc SetCanBeOrdered(SetCanBeOrderedRequest) returns (StatusResponse);
    rpc DeleteProductById(DeleteProductRequest) returns (StatusResponse);
    rpc ProductExists(ProductExistsRequest) returns (StatusResponse);
    rpc GetParentCardId(GetParentCardIdRequest) returns (GetParentCardIdResponse);
    rpc UpdateParentCardId(UpdateParentCardIdRequest) returns (StatusResponse);

    rpc AddImagesToProduct(AddImagesToProductRequest) returns (StatusResponse);
    rpc DeleteImagesFromProduct(DeleteImagesFromProductRequest) returns (StatusResponse);
    rpc AddAttributesToProduct(AddAttributesToProductRequest) returns (StatusResponse);
    rpc DeleteAttributesFromProduct(DeleteAttributesFromProductRequest) returns (StatusResponse);
}

message ProductGrpc
{
    string productId = 1;   
    string ownerId = 2;
    string parentCardId = 3;
    ProductType type = 4;
    string name = 5;
    string description = 6;    
    int32 price = 7;
    int32 stockQuantity = 8;
    string createdAt = 9;
    string updatedAt = 10;
    repeated string imageURLs = 11;
    repeated ProductAttributeGrpc attributes = 12;
    bool canBeOrdered = 13;
}

enum ProductType{
    UNKNOWN_TYPE = 0;
    SHIRTS = 1;
}

enum AttributeKey{  
    UNKNOWN_KEY = 0;
    BRAND = 1;
    VOLUME = 2;
}

message ProductAttributeGrpc
{ 
    AttributeKey key = 1; 
    string value = 2;
}

message StatusResponse
{
    bool status = 1;
    string reason = 2;
}

message CreateProductRequest
{    
    string ownerId = 1;   
    string name = 2;
}

message GetProductsByIdsRequest
{
	repeated string productIds = 1;
}

message GetProductsByIdsResponse
{
	StatusResponse status = 1;
	repeated ProductGrpc products = 2;
}

message GetAllProductsByOwnerIdRequest
{
    string ownerId = 1;
}

message GetAllProductsByOwnerIdResponse
{  
    StatusResponse status = 1;
    repeated ProductGrpc products = 2;
}

message GetProductRequest
{
    string productId = 1;
}

message GetProductResponse
{
    StatusResponse status = 1;
    ProductGrpc product = 2;
}

message DeleteProductRequest
{
    string productId = 1;
}

message UpdateProductRequest
{
    string productId = 1;   
    string name = 2;
    ProductType type = 3;
    string description = 4;    
    int32 price = 5; 
    int32 stockQuantity = 6;   
}

message SetCanBeOrderedRequest
{
    string productId = 1;
    bool canBeOrdered = 2;
}

message AddImagesToProductRequest
{
    string productId = 1;
    repeated string imageURLs = 2;
}

message DeleteImagesFromProductRequest
{
    string productId = 1;
    repeated string imageURLs = 2;
}

message AddAttributesToProductRequest
{
    string productId = 1;
    repeated ProductAttributeGrpc attributes = 2;
}

message DeleteAttributesFromProductRequest
{
    string productId = 1;
    repeated AttributeKey key = 2; 
}

message ProductExistsRequest
{
    string productId = 1;
}

message GetParentCardIdRequest
{
    string productId = 1;
}

message GetParentCardIdResponse
{
    StatusResponse status = 1;
    string parentCardId = 2;
}

message UpdateParentCardIdRequest
{
    string productId = 1;
    string parentCardId = 2;
}