syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

package productvariant.v1;

option csharp_namespace = "ProductVariantService.Api.Grpc.V1.Protos";

service ProductVariantService {
	rpc CreateProductVariant(CreateProductVariantRequest) returns (google.protobuf.Empty);
    rpc UpdateProductVariantInfo(UpdateProductVariantInfoRequest) returns (google.protobuf.Empty);

    rpc AddProductVariantImage(AddProductVariantImageRequest) returns (google.protobuf.Empty);
    rpc RemoveProductVariantImage(RemoveProductVariantImageRequest) returns (google.protobuf.Empty);

    rpc ReorderProductVariantImages(ReorderProductVariantImagesRequest) returns (google.protobuf.Empty);
    rpc UpdateProductVariantImageAlt(UpdateProductVariantImageAltRequest) returns (google.protobuf.Empty);

    rpc DeleteProductVariant(DeleteProductVariantRequest) returns (google.protobuf.Empty);
}

message DimensionsDto {
    double length = 1;
    double width = 2;
    double height = 3;
    string unit = 4;
}

message WeightDto {
    double value = 1;
    string unit = 2;
}

message CreateProductVariantRequest {
    string vendor_id = 1;
    string product_id = 2;

    DimensionsDto dimensions = 3;
    WeightDto weight = 4;

    string barcode = 5;
    string sku = 6;

    map<string, string> attributes = 7;
}

message UpdateProductVariantInfoRequest {
    string vendor_id = 1;
    string product_variant_id = 2;
    string barcode = 3;
    string sku = 4;
    DimensionsDto dimensions = 5;
    WeightDto weight = 6;
}

message AddProductVariantImageRequest {
    string vendor_id = 1;
    string product_variant_id = 2;
    string url = 3;
    string alt = 4;
}

message RemoveProductVariantImageRequest {
    string vendor_id = 1;
    string product_variant_id = 2;
    string image_id = 3;
}

message ReorderProductVariantImagesRequest {
    string vendor_id = 1;
    string product_variant_id = 2;
    repeated string ordered_image_ids = 3;
}

message UpdateProductVariantImageAltRequest {
    string vendor_id = 1;
    string product_variant_id = 2;
    string image_id = 3;
    string new_alt = 4;
}

message DeleteProductVariantRequest {
    string vendor_id = 1;
    string product_variant_id = 2;
}