using MediatR;

namespace ProductVariantService.Application.Features.IntegrationEventHandlers.CharacteristicSnapshot.DeleteCharacteristicSnapshot;

public sealed record DeleteCharacteristicSnapshotCommand(Guid CharacteristicId) : IRequest;